missing pytest handling

diff --git a/aihub_action/test_backend/action.yml b/aihub_action/test_backend/action.yml
--- a/aihub_action/test_backend/action.yml
+++ b/aihub_action/test_backend/action.yml
@@ -87,19 +87,22 @@ runs:
     - name: Run Tests with Coverage and Generate Report
       shell: bash
       run: |
-        if poetry run pytest -m "not azure" --cov=. \
-                             --cov-report=xml:coverage.xml \
-                             --cov-report=term-missing \
-                             --junitxml=pytest.xml; then
-          echo "Tests ran successfully."
-        else
-          if [ $? -eq 5 ]; then
-            echo "No tests found. Skipping..."
-          else
-            echo "TEST_FAIL=true" >> $GITHUB_ENV
-          fi
+        pytest_exit_code=0
+        poetry run pytest -m "not azure" --cov=. \
+                         --cov-report=xml:coverage.xml \
+                         --cov-report=term-missing \
+                         --junitxml=pytest.xml || pytest_exit_code=$?
+    
+        if [[ $pytest_exit_code -eq 5 ]]; then
+          echo "⚠️ No tests found! Creating an empty pytest.xml..."
+          echo '<?xml version="1.0" encoding="UTF-8"?><testsuites></testsuites>' > pytest.xml
+          echo "NO_TESTS_FOUND=true" >> $GITHUB_ENV
+        elif [[ $pytest_exit_code -ne 0 ]]; then
+          echo "❌ Some tests failed!"
+          echo "TEST_FAIL=true" >> $GITHUB_ENV
         fi
       working-directory: ${{ inputs.working_directory }}
+
 
     - name: Stop Docker services (if started)
       if: inputs.docker_compose_paths != ''
